name: MidiBanks
main: net.myshelter.minecraft.midibanks.MidiBanks
author: Protected and jfmherokiller
version: 1.5 API 1.2.4-R1.0
commands:
  midi:
    description: Auxiliary MIDI commands
    usage: /<command> [arguments]
