name: MidiBanks
main: net.myshelter.minecraft.midibanks.MidiBanks
authors: [Protected, jfmherokiller]
version: 1.5 API 1.2.4-R1.0
description: A music helper plugin
commands:
  midi:
    description: Auxiliary MIDI commands
    usage: /<command> [arguments]
