name: MidiBanks
main: net.myshelter.minecraft.midibanks.MidiBanks
authors: [Protected, jfmherokiller]
version: 2.4
description: A music helper plugin
commands:
  midibanks:
    description: Auxiliary MIDI commands
    usage: /<command> [arguments]
permissions:
    midibanks.*:
        description: Gives access to all midibanks commands
        children:
            midibanks.cmd: true
            midibanks.can-create: true
            midibanks.can-use: true
    midibanks.cmd:
        description: allows you to access the cmds
        default: false
    midibanks.can-create:
        description: allows you to create midi banks
        default: false
    midibanks.can-use:
        description: allows you to use the signs
        default: false