name: MidiBanks
main: net.myshelter.minecraft.midibanks.MidiBanks
author: Protected and jfmherokiller
version: 1.0 API 1.2.3-R0.1
commands:
  midi:
    description: Auxiliary MIDI commands
    usage: /<command> [arguments]
